---
title: "CV"
author: "Ethan Duvall"
date: "9/30/2020"
output: html_document
---

## **Education**

### PhD, Cornell University | 2020-Current
Ecology and Evolutionary Biology, Dr. Alex Flecker Lab

### BS, Western Washington University | 2016-2019
Environmental Science, Terrestrial Ecology Emphasis 

## **Honors and Awards**

• Andrew '78 & Margaret Paul Graduate Fellowship in the Life Sciences: 2023

• Amazon Center for Environmental Education and Research (ACEER) Conservation Fellow: 2022

• Theodore Gordon Flyfishers (TGF) Scholar Award: 2021

• Cornell University First-year Graduate Fellow in Life Sciences: 2020
 
• Thomas Henry Huxley Award Recipient – *"This award recipient demonstrated exceptional scholastic achievement and has been involved in the community, served Huxley College, and has shown all-around excellence in environmental studies”* 2019

• Honorary Commencement Speaker - Western Washington University, Huxley College of the Environment: 2019


## **Publications** 

•	**Duvall, E.** and McLaughlin, J. (<span style="color:red">*In Review*</span>). Evaluating river-dependent birds as restoration indicators after Elwha dam removals

• **Duvall, E.**, Griffiths, B., Clauss, M., and A. Abraham (<span style="color:red">*In Review*</span>). Allometry of sodium requirements and   mineral lick use among herbivorous mammals.  

• Abraham A., **Duvall, E.**, le Roux, E., Ganswindt, A., Clauss, M., Doughty, C., and A. Webster (<span style="color:red">*In Review*</span>) Anthropogenic supply of nutrients in a wildlife reserve may compromise conservation success.

• **Duvall, E.**, Schwabe, E., and K. Steensma (<span style="color:red">**2023**</span>). A win-win between farmers and an apex-predators: investigating the relationship between bald eagles and dairy farms. *Ecosphere* https://doi.org/10.1002/ecs2.4456

• Abraham, A., **Duvall, E.**, Ferraro, K., Webster, A., Doughty, C., le Roux, E., and D. Ellis-Soto. (<span style="color:red">**2022**</span>). Understanding anthropogenic impacts on zoogeochemistry is essential for ecological restoration. *Restoration Ecology* https://doi.org/10.1111/rec.13778 

•	Buchanan, B., Sethi, S., Cuppett, S., Jackman, G., Lung, M., Zarri, L., **Duvall, E.**, et al. (<span style="color:red">**2022**</span>) A machine learning approach to identify barriers in stream networks demonstrates high prevalence of unmapped riverine dams. *Journal of Environmental Management* https://doi.org/10.1016/j.jenvman.2021.113952

•	**Duvall, E.** (<span style="color:red">**2022**</span>). Spatiotemporal responses of bald eagles to changes in salmon carcass availability in the Pacific Northwest. *Northwest Science* Vol 95. https://doi.org/10.3955/046.095.0306 

## **Presentations**

• **Duvall, E.**, Flecker, A., Derry, L. (<span style="color:red">**2022**</span>) Stoichiometry of birds and implications for ecosystem ecology. *Ecological Society of America (ESA)*

• **Duvall, E.**, McLaughlin, J. (<span style="color:red">**2022**</span>) Riverbird responses to dam removals on the Elwha River. *Salish Sea Ecosystem Conference*

•	**Duvall, E.**, McLaughlin, J. (<span style="color:red">**2021**</span>) Riverbird responses to dam removals on the Elwha River *Olympic National Park Science Symposium*

•	**Duvall, E.** (<span style="color:red">**2019**</span>) Nooksack River Bald Eagles: Current Status and Conservation Recommendations. *Whatcom Wildlife Advisory Committee*

•	**Duvall, E.** (<span style="color:red">**2019**</span>) Measuring restoration progress using river-dependent birds: Lessons from Elwha dam removal. *Salish Sea Ecosystem Conference* https://ssec.confex.com/ssec/2020/meetingapp.cgi/Paper/5736

•	**Duvall, E.**, Jones, R., and Pollack, S. (<span style="color:red">**2018**</span>) River-dependent bird responses to impacts of dam removal. *Western Washington University Scholars Week*

## **Articles and Links**

•	Duvall, E. (2019, December 11). Eagles, Salmon, and a Free-flowing River [Blog post]. Retrieved from 
https://www.americanrivers.org/2019/12/eagles-salmon-and-a-free-flowing-river/

•	Duvall, E. (2020, June 20). Why save water in the PNW? [Blog post]. Retrieved from https://weneedwater.org/why-conserve-water-in-the-pnw/

•	Speech given at the 2019 Huxley College of the Environment commencement ceremony:
“2019 Huxley Graduation THH Winner Ethan Duvall Speech”
https://www.youtube.com/watch?v=t4MsRdLxKiE

•	Short film about my undergraduate research, produced by Western Washington University:
“WWU Give Day ’19 Video| Ethan Duvall | Huxley Ecology Research”
	https://vimeo.com/336206305

•	Article about my research on the Elwha River, written by the Western Front:
“Environmental Science Students Analyze a River Reborn”
http://www.westernfrontonline.com/2019/01/10/environmental-science-students-analyze-a-river-reborn/

•	Video feature about the importance of education and action in conservation issues:
"Education and Action - Luke Duvall #WeNeedWater"
https://www.youtube.com/watch?v=FYlf_vfEEno&t=30s

•	Video I directed promoting community engagement in keeping rivers clean:
"Protecting Clean Water as a COmmunity #WeNeedWater"
https://www.youtube.com/watch?v=pmuJgfw4vSE

## **Professional Experience**

•	2018 – 2020
GIS Program Lead, CASCADE WATER ALLIANCE

•	2017 - 2018 
Environmental Intern, CASCADE WATER ALLIANCE

•	2017 – 2018 
Field Technician, HUXLEY COLLEGE & WASHINGTON DEPARTMENT OF FISH AND WILDLIFE

•	2014 - 2017 
Outdoor Recreational Guide, COMPASS OUTDOOR ADVENTURES

## **Leadership Positions**

• President: Tropical Biology & Conservation GSA, Cornell University: 2022-current

• Vice President: Tropical Biology & Conservation GSA, Cornell University: 2021-2022

• Treasurer: Biogeochemistry GSA, Cornell University: 2021-2022

• Committee Member: North Bend Parks and Recreation: 2014-2016

## **Activities and Volunteer Work**

• Youth Mentor: The Learning Web, Ithaca, NY: 2020-current

• Graduate Student Recruitment Committee Member, Department of EEB: 2020-current

•	Volunteer: Hawk Watch, Chelan Ridge Raptor Banding site: 2018

•	Volunteer: Salish Sea Ecosystem Conference; 2018

•	Volunteer: Wildlife Monitoring Technician, WWU Department of Biology: 2017-2018

•	Volunteer: Vine Deloria Jr. Indigenous Studies Symposium: 2019

•	High school varsity soccer Captain, MVP, and 1st Team All-Conference Player: 2014-2016 

• Co-founder: Be the Change Leadership Conference: 2011-current


## **Skills and Certificates**

•	Certificates: River Studies and Leadership; River Science; ACA Swiftwater Rescue Certificate: Level 2 

• GIS software: ArcGIS Pro; ArcGIS Online; ESRI Products; QGIS

• Statistical languages/programs: R, RStudio, Python, SQL, MATLAB

• Other software: Dragonfly, Google Earth engine, Ableton 

• Spatial data processing: Remote sensing; image analysis; LiDAR; radio telemetry

• Wildlife survey methods: songbirds, riverbirds, raptors, carnivores, amphibians


## **Organizations and Affiliations**

•	Ecological Society of America member 2022-current

•	Northwest Scientific Association member 2021-current

•	Washington Chapter of the Wildlife Society member 2019-2020

•	River Management Society member 2019-2020

•	Puget Sound ESRI User Group member 2018-2020


